POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "name": "Test",
  "username": "test",
  "password": "password",
  "email": "test@gmail.com"
}

###

POST http://localhost:8080/api/registration/request-new-token
Content-Type: application/json

{
  "name": "Kto-to",
  "username": "kto-to",
  "password": "password",
  "email": "kto-to@gmail.com"
}

###

POST http://localhost:8080/api/registration/confirm
Content-Type: application/json

{
  "token": "ec5178df-57bd-4ba4-a2b7-05934937788f"
}

###

POST http://localhost:8080/api/authentication
Content-Type: application/json

{
  "username": "katya",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("auth_token", response.body.token)
});
%}

###

GET http://localhost:8080/api/games
X-Token: {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

GET http://localhost:8080/api/games/21
X-Token: {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

GET http://localhost:8080/api/games/not-approved
X-Token: {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/api/games/not-approved/11/approve
Content-Type: application/json
X-Token: {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/api/games
Content-Type: application/json
X-Token: {{auth_token}}

{
  "name": "Test Game 3",
  "releaseDate": "2022-01-22",
  "content": "Test Game content 2",
  "coverage": "test-cover.png",
  "status": "TODO",
  "genre": "RPG"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/api/games/not-approved/21/return
Content-Type: application/json
X-Token: {{auth_token}}

{
  "comment": "Please, edit your content"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/api/games/21/edit
Content-Type: application/json
X-Token: {{auth_token}}

{
  "name": "Test Game 3",
  "releaseDate": "2022-01-22",
  "content": "Test Game content 2",
  "coverage": "test-cover.png",
  "status": "TODO",
  "genre": "RPG"
}

###