POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "name": "Alina",
  "username": "alina",
  "password": "password",
  "email": "alina@shukurov.com"
}

###

POST http://localhost:8080/api/authentication
Content-Type: application/json

{
  "username": "petya",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("auth_token", response.body.token)
});
%}

###

POST http://localhost:8080/api/registration/confirm
Content-Type: application/json

{
  "token": "d338d041-7315-4f96-973a-9423b35b632f"
}

###