POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "name": "Petya",
  "username": "petya",
  "password": "password",
  "email": "petya@mail.ru"
}

###

POST http://localhost:8080/api/authentication
Content-Type: application/json

{
  "username": "petya",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("auth_token", response.body.token)
});
%}

###